version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: hostingin-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: hostingin_db
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - hostingin-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hostingin-backend
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=hostingin_db
      - JWT_SECRET=${JWT_SECRET:-change-this-secret-key-in-production}
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRATION_MINUTES=1440
      - CORS_ORIGINS=*
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    networks:
      - hostingin-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hostingin-frontend
    restart: unless-stopped
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - hostingin-network

volumes:
  mongodb_data:

networks:
  hostingin-network:
    driver: bridge
